### ISSUE TITLE
Scraping usernames from dataframe

### ISSUE THREAD

**Issue by faiqmari** [MartinBeckUT/TwitterBot#1]
Hello, 
I am trying to use the code to scrape twitter accounts based on a an excel sheet, and then populate new columns in it with the data scraped. 
This is what I added to the code: 

`df = pd.read_excel('Sheet.xlsx')

usernames = df["Twitter_username"] 

for username in usernames:
    username_tweets_to_csv(username, count)`

But I want to populate the original file (or the dataframe generated from it) so how can I do that? 

(I'm new to programming and this is the first time I use GitHub so I hope I'm using the issues feature correctly—for some reason I couldn't comment on the Medium article)

**Comment by MartinBeckUT** [comment]
Hi,

Great to hear you're getting into programming. You can use the issues feature for a variety of things. Honestly, this problem isn't too bad and most troubleshooting issues you can usually find some kind of help by Google searching, there's tons of StackOverflow questions that have been answered.

I've got time so I don't mind helping. Your problem looks two fold, you want to scrape several different usernames and want to put it back into the original file.

The way my code was made originally I created a new dataframe per username. Since you want all the data in one place instead of several dataframes you want to look into one of two options from the python pandas library. Google search how to append or merge dataframes to find which is more appropriate for what you want. After choosing one of the options modify the code so that everytime you scrape new tweets from another username it'll just append the data to the end of the dataframe you already had. That way when you're done scraping you have a single dataframe that contains all the tweets from all of the usernames you scraped. 

When you're done it's pretty simple after that, you just do a simple df.to_excel('Sheet.xlsx') or whatever new excel file you want to create.

Let me know if that helped so I can close this issue!

**Comment by faiqmari** [comment]
Hi Martin, 

Many thanks for your response, I really appreciate it. 
I learned .append recently and you just reminded me of that, I will try it out and let you know. Nonetheless, my confusion remains whether the append order (or what I was trying before) should be inside the loop or inside the username_tweets_to_csv function; what I couldn't understand is why the tweets_df you create in your function cannot be 'caught' (for example printed etc.) from outside the function. I don't know if I'm using the correct terms or making any sense. But anyway, I will keep trying. 

Sincerely, 
Faiq

**Comment by MartinBeckUT** [comment]
Hi Faiq,

Hopefully I'm understanding your response correctly. First thing I need to understand is whether you're running a jupyter notebook or running a .py file in an IDE or text editor?

It might be a programmatic thing because usually things that are created within methods cannot be called outside the method because they only exist within the method scope. However, if you're running a jupyter notebook you should probably still be able to call the data frame since it does generate it within memory?

As for where to place the append, first you'll have to generate an initial dataframe which is just the first username, then you can create a loop to append each concurrent usernames data onto the first data frame. If you don't have an initial dataframe I know I've had this problem where I created a loop to append dataframes together without an initial dataframe and it obviously get's confused.

Let me know if that helps?

**Comment by faiqmari** [comment]
Hi Martin, 

Thanks for the response, I was late to notice it. I am using jupyter, but it's great that pointed out the difference between the two and confirmed that things created within methods could be "called" (now I know the correct term!) outside the method. I suppose from your answer that the initial data frame can be created anywhere in jupyter not only within the method since it will be in its memory. I will try this again and I hope it works for me this time. 

Thank you, it was helpful

**Comment by MartinBeckUT** [comment]
Problem appears to be solved. The user wanted to append new data to the same dataframe by scraping using a list of usernames.
